export const FETCH_ALBUM_SUCCESS = 'FETCH_ALBUM_SUCCESS';
export const ADD_PHOTO = 'ADD_PHOTO';
export const FETCH_PHOTO_SUCCESS = 'FETCH_PHOTO_SUCCESS';
export const FETCH_USER_SUCCESS = 'FETCH_USER_SUCCESS';
export const FETCH_FAIL = 'FETCH_FAIL';
